### ISSUE TITLE
TypeError: 'coo_matrix' object is not subscriptable

### ISSUE THREAD

**Issue by jjializhu** [single-cell-genetics/MQuad#17]
Traceback (most recent call last):

    _ad = np.squeeze(np.asarray(self.ad[_x, _y]))
TypeError: 'coo_matrix' object is not subscriptable

**Comment by aaronkwc** [comment]
Hi @jjializhu, can you please elaborate a bit on the issue? e.g. What was the input?

**Comment by drSnuce** [comment]
I am encountering the same issue.
my input is two matrices, AD and DP
mquad -m cellSNP.tag.AD.mtx,cellSNP.tag.DP.mtx -o ./mquad/ --minDP 5 -p 20

output
[MQuad] Loading matrix files ...
16569 variants detected...
Variant names detected...
CPUs used: 20, batch size: 128 
Fitting in sparse mode...
Initializing fit(mode: deltaBIC) on 16569 variants...
Traceback (most recent call last):
  File "/Users/nikolay/anaconda3/envs/python-3.11.3/bin/mquad", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/site-packages/mquad/mquad_CLI.py", line 132, in main
    df = mdphd.fit_deltaBIC(
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/site-packages/mquad/mquad_batch_mixbin.py", line 142, in fit_deltaBIC
    results = pool.starmap_async(fit_batch, self._batchify(batch_size, x, y, valid_row_sizes)).get()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/multiprocessing/pool.py", line 382, in starmap_async
    return self._map_async(func, iterable, starmapstar, chunksize,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/multiprocessing/pool.py", line 478, in _map_async
    iterable = list(iterable)
               ^^^^^^^^^^^^^^
  File "/Users/nikolay/anaconda3/envs/Python-3.11.3/lib/python3.11/site-packages/mquad/mquad_batch_mixbin.py", line 80, in _batchify
    _ad = np.squeeze(np.asarray(self.ad[_x, _y]))
                                ~~~~~~~^^^^^^^^
TypeError: 'coo_matrix' object is not subscriptable
