### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by FionaMoon** [single-cell-genetics/MQuad#24]
Hi all,
I met dependency conflicts when installing MQuad.
```
Installing collected packages: sklearn, pytz, zipp, tzdata, six, pyparsing, pillow, packaging, numpy, kiwisolver, fonttools, cycler, scipy, python-dateutil, importlib-resources, contourpy, pandas, matplotlib, kneed, vireoSNP, BBMix, mquad
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dynamo-release 1.3.3 requires PATSY>=0.5.1, which is not installed.
dynamo-release 1.3.3 requires scikit-learn>=0.19.1, which is not installed.
dynamo-release 1.3.3 requires statsmodels>=0.9.0, which is not installed.
dynamo-release 1.3.3 requires tqdm, which is not installed.
dynamo-release 1.3.3 requires typing-extensions, which is not installed.
pynndescent 0.5.10 requires joblib>=0.11, which is not installed.
pynndescent 0.5.10 requires scikit-learn>=0.18, which is not installed.
umap-learn 0.5.3 requires scikit-learn>=0.22, which is not installed.
umap-learn 0.5.3 requires tqdm, which is not installed.
Successfully installed BBMix-0.2.1 contourpy-1.1.1 cycler-0.12.0 fonttools-4.42.1 importlib-resources-6.1.0 kiwisolver-1.4.5 kneed-0.8.5 matplotlib-3.7.3 mquad-0.1.7 numpy-1.24.4 packaging-23.1 pandas-2.0.3 pillow-10.0.1 pyparsing-3.1.1 python-dateutil-2.8.2 pytz-2023.3.post1 scipy-1.10.1 six-1.16.0 sklearn-0.0.post9 tzdata-2023.3 vireoSNP-0.5.8 zipp-3.17.0
```
I've tried to install dependency by myself but also failed.
Anyone can help?

**Comment by FionaMoon** [comment]
I've installed all dependencies and still got errors when running the example.
```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by aaronkwc** [comment]
Hi @FionaMoon ,

is there a line number that indicate where the error happened? I did a search and did not find the use of `np.float` in the code.

**Comment by FionaMoon** [comment]
I solve this problem by install lower version of numpy.



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/10/2023 02:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [single-cell-genetics/MQuad] Dependency conflicts (Issue #24) |

@aaronkwc Just to chime in - I got a similar error in this: error message pasted below:

Traceback (most recent call last):
File "/home/daniel/.local/bin/mquad", line 8, in
sys.exit(main())
File "/home/daniel/.local/lib/python3.10/site-packages/mquad/mquad_CLI.py", line 138, in main
df = mdphd.fit_deltaBIC(
File "/home/daniel/.local/lib/python3.10/site-packages/mquad/mquad_batch_mixbin.py", line 142, in fit_deltaBIC
results = pool.starmap_async(fit_batch, self._batchify(batch_size, x, y, valid_row_sizes)).get()
File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
raise self._value
AttributeError: module 'numpy' has no attribute 'float'.
np.float was a deprecated alias for the builtin float. To avoid this error in existing code, use float by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.float64 here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

But I don't see anything amiss in either the mquad_CLI.py, nor the mquad_batch_mixbin.py files.

Any help would be greatly appreciated!

**Comment by danieljrichard** [comment]
I also found a solution; it looks like it's one of the dependencies that's the issue; this fixes it:
sed -i -e 's/np.float/float/g' /home/daniel/.local/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py

**Comment by aaronkwc** [comment]
So sorry for missing the discussion - I have been really busy lately.

As @danieljrichard says, it seems the `np.float` line is used in the BBMix package which is one of the dependencies. 
However, I am not the maintainer of that package.

I can notify the maintainer of BBMix to update its code to follow numpy's version update. In the meantime, @FionaMoon 's solution make a lot of sense if you do not mind the slight inconvenience.

Will leave this issue open for now until I find a permanent solution. Thanks all for the discussion.

**Comment by aaronkwc** [comment]
Hi all,

BBMix has been updated to include the latest changes in numpy dtype. Please update BBMix and try MQuad again.
